### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by vicent303** [maeve07/RCA#15]
运行gen_labels.py时出现的报错
![QQ截图20230308201551](https://user-images.githubusercontent.com/115331602/223711409-02f915a7-6b85-41bf-a87b-79fd3c6bd492.jpg)

**Comment by vicent303** [comment]
> 

请问这是什么问题呢？

**Comment by tfzhou** [comment]
Hi @vicent303 , thanks for your interests to our work. I am not familiar with the code. but I'd like to help fix this issue since many others encounter this as well. 

But before that, could you provide more debug info? It seems to me that `v` in below code is empty.
https://github.com/maeve07/RCA/blob/d410a96472580ff980bf89ea250b2c82aadca795/gen_labels.py#L32 

That means cam_dict is probably empty. Could you check this first? In addition, I would suggest to confirm the paths in Line 18 and Line 19.

**Comment by vicent303** [comment]
Thank you for your reply! I have debugged the code and found that the orig folder is generated by the program itself, but it is an empty folder, so does it cause this error when the orig folder is used as the path to add_path?What should be passed inside the orig folder? See lines 22 and 69 for the exact code.
I hope you'll understand as I'm limited, so there may be some things I can't notice in time! I look forward to your reply!

> Hi @vicent303 , thanks for your interests to our work. I am not familiar with the code. but I'd like to help fix this issue since many others encounter this as well.
> 
> But before that, could you provide more debug info? It seems to me that `v` in below code is empty.
> 
> https://github.com/maeve07/RCA/blob/d410a96472580ff980bf89ea250b2c82aadca795/gen_labels.py#L32
> 
> That means cam_dict is probably empty. Could you check this first? In addition, I would suggest to confirm the paths in Line 18 and Line 19.

Thank you for your reply! I have debugged the code and found that the orig folder is generated by the program itself, but it is an empty folder, so does it cause this error when the orig folder is used as the path to add_path?What should be passed inside the orig folder? See lines 22 and 69 for the exact code.
I hope you'll understand as I'm limited, so there may be some things I can't notice in time! I look forward to your reply!

> reply
